/**
 * Public types for Stake Engine integration.
 *
 * The thick `StakeBridge` wrapper translates between Stake's RGS API
 * (single `Play()` returning a pre-generated "book" of all events) and
 * our streaming protocol (one PLAY_REQUEST per spin / free spin / pick).
 *
 * Game developers ship one extra artefact per game: a `BookAdapter` that
 * knows how to slice an RGS round into per-segment `data` payloads.
 */

import type {
  SessionData,
  PlayResultPayload,
  GameConfigData,
} from '@energy8platform/game-sdk/protocol';

// ─── Stake RGS round / book shapes ───────────────────────────────────

/** Raw shape returned by `/wallet/play`. */
export interface StakeRound<TBook = unknown> {
  /** Bet identifier on Stake's side. */
  betID: number;
  /** Total payout multiplier for the whole round (final). */
  payoutMultiplier: number;
  /** Cost multiplier for the whole round (e.g. 1 for spin, >1 for buy bonus). */
  costMultiplier?: number;
  /** Whether the round is currently active (i.e. needs `EndRound`). */
  active: boolean;
  /** Bet mode this round was played at. */
  mode: string;
  /** Last `/bet/event` value reported, if any. */
  event?: string;
  /** The "book" — game-specific event sequence pre-generated by the math SDK. */
  state: TBook;
  /** Currency-major bet amount, optional. */
  amount?: number;
}

/** Replay-mode URL parameters. Present only when the page was launched as a replay. */
export interface StakeReplayParams {
  /** Game identifier (UUID). Required by Stake. */
  game: string;
  /** Math version (e.g. `'1'`, `'2'`). Required by Stake. */
  version: string;
  /** Bet mode used in the original round. Required by Stake. */
  mode: string;
  /** Event/simulation ID to replay. Required by Stake. */
  event: string;
  /**
   * ISO 4217 currency code from the URL. Optional per the spec — the
   * bridge falls back to `'USD'` if the URL doesn't include one.
   */
  currency: string;
  /**
   * Original bet amount in minor units (× API_MULTIPLIER). Optional
   * per the spec — the bridge falls back to `0` when omitted.
   */
  amount: number;
}

/**
 * Stake URL parameters parsed from the iframe / host page location.
 *
 * Either `sessionID` (live wallet session) or `replay` (historical
 * replay) is set, never both. The bridge picks its operating mode
 * based on which one is present.
 */
export interface StakeUrlParams {
  rgsUrl: string;
  lang: string;
  device: 'desktop' | 'mobile';
  /** Live wallet session id. Present unless `replay` is. */
  sessionID?: string;
  /** Replay context. Present when the page was launched as a replay. */
  replay?: StakeReplayParams;
  /** Operator marked the session as social-casino (e.g. via `?social=true`). */
  social?: boolean;
  /** Demo / free-play launch (`?demo=true`). No real balance is affected. */
  demo?: boolean;
  /**
   * Display currency from the URL (`?currency=USD`). Wallet sessions
   * trust `Authenticate.balance.currency` over this; replay launches
   * fall back to it when no in-band currency is available.
   */
  currency?: string;
}

// ─── Adapter contract ────────────────────────────────────────────────

/**
 * Context passed to a `BookAdapter` so it can produce sensible per-segment
 * payloads without re-deriving common round metadata.
 */
export interface RoundContext {
  /** Stake bet mode (e.g. 'BASE', 'BONUS'). */
  mode: string;
  /** Our SDK action that triggered this round (e.g. 'spin', 'buy_bonus'). */
  triggerAction: string;
  /** Bet amount in major currency units (decimal, the same units the game sees). */
  betAmount: number;
  /** Final payout multiplier reported by RGS. */
  payoutMultiplier: number;
  /** Player currency (e.g. 'USD'). */
  currency: string;
  /** Round ID (string form of `round.betID`). */
  roundId: string;
}

/**
 * One playable segment of a round.
 *
 * The bridge synthesises `roundId`, `currency`, `gameId`, `balanceAfter`,
 * `creditPending` and the running totals — the adapter only needs to
 * describe what the game should render and what the next valid actions are.
 */
export interface BookSegment<TGameData = Record<string, unknown>> {
  /**
   * Action label this segment represents (e.g. 'spin', 'free_spin', 'pick').
   * The bridge surfaces this back to the game via `PlayResult.action`.
   */
  action: string;
  /** Game-specific render data (matrix, win_lines, multiplier, picks, …). */
  data: TGameData;
  /** Win produced by this segment alone, in major currency units (decimal). */
  winThisSegment: number;
  /**
   * Actions the game may invoke next.
   *
   * For non-final segments include the action that drives the next segment
   * (typically `'free_spin'` or `'pick'`). For the final segment include
   * the actions available for the next round (e.g. `['spin', 'buy_bonus']`).
   */
  nextActions: string[];
  /**
   * Optional override for the synthesised session metadata.
   * If omitted, the bridge generates `{ spinsRemaining, spinsPlayed, totalWin }`
   * from the segment array index.
   */
  session?: Partial<SessionData> | null;
  /**
   * Optional opaque marker the bridge will forward to `/bet/event`
   * after this segment is acknowledged. Used for mid-round recovery.
   * If omitted the bridge sends `seg-<index>`.
   */
  progressMarker?: string;
  /**
   * If your math model emits a bonus free-spin grant on this segment,
   * set it here; the bridge will surface it on the corresponding
   * `PlayResult.bonusFreeSpin`.
   */
  bonusFreeSpin?: { grantId: number; remainingSpins: number };
}

/**
 * Per-game adapter that translates a Stake RGS round (book) into the
 * streamed segments our SDK protocol speaks.
 *
 * Adapters are pure functions of the RGS round — they MUST NOT make
 * network calls or rely on global state. The bridge drives the network.
 */
export interface BookAdapter<TBook = unknown, TGameData = Record<string, unknown>> {
  /**
   * Slice a round's book into the ordered list of segments to stream
   * back to the game, one per player-visible spin/free-spin/pick.
   */
  splitRound(book: TBook, ctx: RoundContext): BookSegment<TGameData>[];

  /**
   * Optionally compute the segment index to resume from when the
   * player reconnects mid-round. `lastEvent` is whatever value was
   * last reported via `/bet/event` (or `undefined` if none).
   *
   * Default behaviour (when this function is not provided): resume
   * from the start of the book — the player re-watches all animations
   * but no math is replayed on the server.
   */
  resumeFrom?(book: TBook, lastEvent: string | undefined, ctx: RoundContext): number;

  /**
   * Optional hook to massage the `GameConfigData` published in `INIT`.
   * Useful if your math SDK exposes betModes / paytables that the game
   * wants to read at startup. Receives the bare config the bridge
   * built from `Authenticate.config` and may return a replacement.
   */
  enrichConfig?(config: GameConfigData): GameConfigData;
}

// ─── Adapter loader ──────────────────────────────────────────────────

/**
 * Function signature exported by an adapter file at
 * `<assetsUrl>/stake-adapter.js`.
 *
 * The default export must be either a `BookAdapter` instance or a
 * factory function returning one (potentially async).
 */
export type AdapterModule<TBook = unknown, TGameData = Record<string, unknown>> =
  | BookAdapter<TBook, TGameData>
  | ((opts?: AdapterFactoryOptions) => BookAdapter<TBook, TGameData> | Promise<BookAdapter<TBook, TGameData>>);

export interface AdapterFactoryOptions {
  /** Bet mode currently in play. */
  mode: string;
  /** Stake URL parameters, in case the adapter needs lang / device. */
  url: StakeUrlParams;
}

// ─── Bridge constructor options ──────────────────────────────────────

/** Map our SDK action names to Stake bet modes. */
export interface ModeMap {
  /** Default mode used when an action is not present in the map. */
  default?: string;
  /** Per-action mapping, e.g. `{ spin: 'BASE', buy_bonus: 'BONUS' }`. */
  [action: string]: string | undefined;
}

export interface StakeBridgeOptions {
  /**
   * Run the bridge in-process with the game (no iframe boundary).
   *
   * When `true`, the bridge talks to the game's `CasinoGameSDK` via
   * the in-memory `MemoryChannel` instead of `window.postMessage`.
   * The game must also instantiate `CasinoGameSDK({ devMode: true })`.
   *
   * **This is the recommended setup for Stake**: the game's own Vite
   * build imports `StakeBridge` and the adapter directly — there is
   * no separate host page or runtime adapter download.
   *
   * When `false` / omitted, `iframe` is required and the bridge
   * speaks postMessage to the iframe.
   */
  devMode?: boolean;
  /**
   * The game iframe element. Required unless `devMode` is `true`.
   */
  iframe?: HTMLIFrameElement;
  /**
   * Map our SDK action → Stake `mode`.
   * If absent the action name is used as-is.
   */
  modeMap?: ModeMap;
  /**
   * The per-game `BookAdapter` (or async factory).
   *
   * In Vite/webpack-built games this is just an `import` of the
   * adapter module — no runtime download is involved. Pass either
   * the adapter object directly or a factory function.
   */
  adapter?: BookAdapter | AdapterModule;
  /**
   * Escape hatch: load the adapter from a URL via dynamic `import()`.
   *
   * Use only if you genuinely need to ship the adapter detached from
   * the game bundle. Prefer `adapter` for normal Vite builds.
   */
  adapterUrl?: string;
  /** Game identifier surfaced on `PlayResult.gameId`. */
  gameId?: string;
  /**
   * Base URL for game assets, surfaced to the game in `INIT.assetsUrl`.
   * Optional — when omitted the game receives `undefined` (which is
   * fine for in-process mode where the assets are already loaded by
   * the page that hosts the bridge).
   */
  assetsUrl?: string;
  /**
   * Optional override of the location used to read URL parameters
   * (`sessionID`, `rgs_url`, `lang`, `device`). Defaults to
   * `window.location.href`.
   */
  url?: string | URL | Location;
  /** Override the protocol used to call the RGS. Defaults to `'https'`. */
  protocol?: 'http' | 'https';
  /**
   * Enforce that bet amounts match `betLevels` from Authenticate.
   * Defaults to `true`.
   */
  enforceBetLevels?: boolean;
  /** `targetOrigin` forwarded to the underlying postMessage `Bridge`. Ignored when `devMode` is true. */
  targetOrigin?: string;
  /** Enable verbose logging. */
  debug?: boolean;
  /**
   * Override the timer used to poll `/wallet/balance` while the player
   * is idle. Defaults to 60 000 ms; set to 0 to disable.
   */
  balancePollMs?: number;
}

// ─── Internal helpers (re-exported for testing / advanced use) ───────

/** Convenience type for a play result the bridge has to materialise. */
export type SegmentResult = PlayResultPayload;
